version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432" # Changement du port hôte pour éviter le conflit

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  tests:
    build: .
    command: bash -c "python manage.py migrate && pytest --ds=blogproject.settings"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgresql://bloguser:blogpass@db:5432/blogdb
      - DJANGO_SETTINGS_MODULE=blogproject.settings
      - PYTHONPATH=/code
      - POSTGRES_HOST=db
      - POSTGRES_DB=blogdb
      - POSTGRES_USER=bloguser
      - POSTGRES_PASSWORD=blogpass
    depends_on:
      - db

volumes:
  postgres_data:
