# Generated by Django 5.2.5 on 2025-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification_enabled',
            field=models.BooleanField(default=True, verbose_name='Notifications activées'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Statut/Humeur'),
        ),
    ]
