# Generated by Django 5.2.5 on 2025-09-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(default='draft', max_length=20, verbose_name='Statut du post'),
        ),
    ]
